# Generated by Django 5.2.7 on 2025-10-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_from',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
