# Generated by Django 5.2.7 on 2025-10-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0002_transaction_cleared_transaction_to_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='first_name',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='last_name',
            new_name='name',
        ),
    ]
