# Generated by Django 5.2.8 on 2025-11-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0003_rename_first_name_account_account_number_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', '-date'], name='Checkbook_t_account_49bfad_idx'),
        ),
    ]
